name: zSpawner
author: Maxlego08
main: fr.maxlego08.spawner.SpawnerPlugin
website: https://groupez.dev
description: Spawner plugin
version: ${project.version}
api-version: 1.13
depend:
  - zMenu
softdepend:
  - zShop
commands: