<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>fr.maxlego08.spawner</groupId>
        <artifactId>zSpawner</artifactId>
        <version>4.2.0</version>
    </parent>

    <artifactId>Core</artifactId>

    <build>
        <finalName>zSpawner-${project.parent.version}</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.6.1</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <shadedArtifactAttached>false</shadedArtifactAttached>
                            <outputFile>${project.build.directory}/${project.build.finalName}.jar</outputFile>
                            <artifactSet>
                                <includes>
                                    <include>fr.maxlego08.spawner:API</include>
                                    <include>fr.maxlego08.sarah:sarah</include>
                                    <include>com.tcoded:FoliaLib</include>
                                </includes>
                            </artifactSet>
                            <relocations>
                                <relocation>
                                    <pattern>fr.maxlego08.sarah</pattern>
                                    <shadedPattern>fr.maxlego08.spawner.sarah</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>com.tcoded.folialib</pattern>
                                    <shadedPattern>fr.maxlego08.spawner.lib.folialib</shadedPattern>
                                </relocation>
                            </relocations>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>


    <dependencies>
        <dependency>
            <groupId>fr.maxlego08.spawner</groupId>
            <artifactId>API</artifactId>
            <version>${project.parent.version}</version>
        </dependency>

        <dependency>
            <groupId>com.tcoded</groupId>
            <artifactId>FoliaLib</artifactId>
            <version>0.5.1</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>com.github.Maxlego08</groupId>
            <artifactId>zTranslator</artifactId>
            <version>1.0.0.0</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>me.clip</groupId>
            <artifactId>placeholderapi</artifactId>
            <version>2.11.6</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>fr.maxlego08.shop</groupId>
            <artifactId>zshop-api</artifactId>
            <version>3.3.1</version>
        </dependency>

        <dependency>
            <groupId>fr.maxlego08.essentials</groupId>
            <artifactId>zessentials-api</artifactId>
            <version>1.0.2.9</version>
        </dependency>

        <dependency>
            <groupId>com.bgsoftware</groupId>
            <artifactId>SuperiorSkyblockAPI</artifactId>
            <version>2025.1</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>fr.maxlego08.sarah</groupId>
            <artifactId>sarah</artifactId>
            <version>1.22</version>
        </dependency>
    </dependencies>
</project>